### ISSUE TITLE
User feel of the sensitivity of focus in SEM and FM

### ISSUE THREAD

**Issue by effting** [delmic/odemis#11]
Sensitivity of the focus is much lower in SEM than in FM due to the much larger depth of focus, especially when using high-NA objective lens. When setting the focus by dragging the mouse while holding the right mouse button the user has to be 'delicate' when focusing the FM and can be 'rough' when focusing the SEM. While physically accurate, it might improve the user feel if we apply a variable gain to the focus operation dependent on the depth of focus.

**Comment by delmic** [comment]
It'd be good to know how we can compute this "depth of focus". Should we have a NA property on the lenses, or a "depth of focus" property? Maybe can it simply be estimated out of the field of view and/or the type of stream (SEM/FM)? 

As a side topic, that information could probably be also used by the auto-focus algorithm to find the best size of the starting step.

**Comment by pieleric** [comment]
Depth of Field is now used, for manual focus and autofocus. Since then, much less users are complaining about the focus.
