### ISSUE TITLE
Save an individual screen

### ISSUE THREAD

**Issue by Physics-Mark** [delmic/odemis#1102]
It would be nice to be able to save an individual display instead of having to save a snap shot.

Suggested to add a right-click menu that allows you to save an individual display as a tiff or text.

For example: If I am processing a data set, I would like to save a single spectra to plot in another program. Or if I am collecting data I would like to save a single spectra without having to collect a whole map or an image.

**Comment by pieleric** [comment]
What you describe seems to be supported via the "Export" functionality. Click on the view that you'd like to save (eg, the spectrum plot), then press the "Export" button. You can then select to store either as a TIFF/PNG (image), or as a CSV (text).

Is that sufficient, or did you mean something different?
