### ISSUE TITLE
Moving the stage in between FM and SEM acquisitions lead to incorrect overlay

### ISSUE THREAD

**Issue by effting** [delmic/odemis#15]
Consider the following use case:
- Acquire an image using the fluorescence microscope
- After the acquisition pause the stream
- Move the stage to a new location
- Acquire an image with the SEM

The resulting image in the combined viewport now combines the FM image of the old stage position with the SEM image at the new stage position.

**Comment by delmic** [comment]
Note that now a warning is displayed in such case. To be decided if that is enough.

**Comment by pieleric** [comment]
Now, in addition to the warning, the stream which are mis-aligned are automatically hidden. Will be available with Odemis v2.5.
