### ISSUE TITLE
Contrast/brightness in Delphi

### ISSUE THREAD

**Issue by effting** [delmic/odemis#19]
_E-mail Matt:_

Strange things have been happening with Brightness/Contrast

* Jumps to a setting that's either far too bright or far too dark
* Couldn't use Odemis to adjust this enough to see anything
* Using the Phenom UI, I could adjust it enough to get an image
* Even then it jumps occasionally, and doesn't always correspond to the setting indicated on the sliding scale on the Phenom UI
* The levels graph on Odemis seems suspiciously geometric in its shape so I'm not sure it's accurately representing the actual data

Is the intention to use Odemis alone to adjust SEM Brightness/Contrast? If so, that doesn't seem to work at the moment. As with the SECOM, it seems to adjust the brightness and contrast in the image from the SEM, rather than adjusting the SEM Brightness/Contrast settings directly.

**Comment by delmic** [comment]
There is now a special brightness/contrast setting for the hardware on the Delphi. In addition, in 8 BPP, the Auto B/C is disabled by default. That should fix all the reported confusion and problem.
