### ISSUE TITLE
Viewport opacity slider works incorrectly

### ISSUE THREAD

**Issue by biermeester** [delmic/odemis#23]
When loading a file containing SEM survey/Spectrum data in the Analysis tab for the first time, the opacity slider does not work in the combined view. (The left side gets assigned the SEM stream and the right the Spectrum stream).

After hiding and showing the SEM survey stream, the left and right streams on the slider are swapped and everything seems to work as it should.

**Comment by delmic** [comment]
fixed in commit 7d2b278d67e6a7f8057daf14101925e04f66bb20
