### ISSUE TITLE
Possible to change the resolution during spot mode

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#27]
On the SECOM, in lens alignment tab, when the spot mode is active, the SEM settings can still be modified.

This means that in spot mode, reducing the scale will increase the resolution, and causing the spot mode to not be correct. Even worse, after spot mode is over, the resolution will be reset to the old one, which causes a cropped acquisition.

The minimum fix is to prevent changes to the SEM settings during spot mode.

**Comment by pieleric** [comment]
Fixed by f675cee97c7fa757aeb65fef12ff36e553bac73b .
Will be available in v2.7 .
