### ISSUE TITLE
Changing the center wavelength of the spectrometer with a slider is useless

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#28]
As noted by Benjamin from AMOLF:
- the slider for the grating position is really not necessary, and actually a pain. You can by accident click on it at positions that will move the grating enormously (such as to several micron) which is completely pointless and nobody is going to use the slider, you always want to move to a specific position, so just typing it in is always going to be easier and faster and more exact (if you click on the slider you might move to 701 nm instead of 700 nm for example I think). So I think it would be better to remove the slider completely. Is there any reason to keep it? Here at Amolf we do not see a reason in any case...
- the units. This is useful for the grating, but also for the pixel size and other places you have to put a length/position. Now it is always in SI, so you have e-9 or something like that, you can easily by accident delete that and have a really strange value. It is not really a problem, but it is not very handy and intuitive. It would probably be better to have everything in nanometers, or to have the units be a little box where you can then choose between nanometers and micrometers (I do not think you would choose something else)... Depending on what you set, now the way the GUI shows the size/position is dependent on what you fill in. So 750 nm will be shown as 750 nm, but 700 nm will be shown as 7e-7m for example...

=> Just provide a number text input, with wavelength in nm.

**Comment by pieleric** [comment]
Since v2.4, the units issue is fixed: the number are shown and read also taking into account the SI prefix. So wavelength is pretty much always displayed in nm (except for some very long wavelength, which is displayed as, eg, 1.2µm).

**Comment by pieleric** [comment]
Fixed by commit 7ab81f11f0e479809b58878c8ffe6c6e7fbe54f1.
