### ISSUE TITLE
Acquisition window should allow to directly see the acquired data

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#30]
In the SECOM, in the acquisition window, at the end of a successful acquisition, the two choices possible are:
 * close (the window)
 * start (a new acquisition)

Instead of starting a new acquisition, the "START" button should be renamed "SHOW", and do the following:
 * Close the window
 * Select the gallery tab
 * Open the acquisition file which was just saved.

**Comment by pieleric** [comment]
As of Odemis v2.4, at the end of a successful acquisition, the "Start" button is changed to "View", and allows to immediately open the data in the Gallery tab.
