### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by thomasaarholt** [delmic/odemis#317]
Just wondering what the thoughts are on supporting python 3 with odemis are. What are the limiting factors?

**Comment by pieleric** [comment]
The hope is that one day we can convert Odemis to Python 3. Most likely, when this will happen, we'll not try to keep compatibility to Python 2.

The current limiting factor of switching is dependencies. There are some (very few) libraries that Odemis uses and which are still only available in Python 2. The main one is wxPython, which has only a development branch (called "Phoenix) available for Python 3.

One of our coding style point is to use division from __future__ everywhere, which should reduce the difficulties to transition to Python 3. I expect the main issues will be in change of behaviour in dict (eg, .keys() is not a list anymore) and str/unicode/bytes reorganisation.

We could have some parts of Odemis already available in Python 3 (in addition to Python 2): model, util, dataio. If you need just one of these modules in Python 3, patches are welcome :-)

**Comment by thomasaarholt** [comment]
Thanks for the response! If I find the time for it, I will see if I can help!
