### ISSUE TITLE
No error when power lost on Zyla

### ISSUE THREAD

**Issue by effting** [delmic/odemis#33]
If the power to the Zyla is lost with Odemis running but no active view, no error is reported to the user in the GUI (it might be in the log file, not checked). The viewport remains black when activating, even when re-applying power to the Zyla.

**Comment by pieleric** [comment]
Still no error reported... but now the image should appear again once the Zyla is powered again (ie, as of release v2.5, Odemis is able to restore communication with a Zyla after reconnection).

**Comment by pieleric** [comment]
In Odemis v3.1, we now show a OS pop-up message when the camera is disconnected, and another one when the connection is successful again.
