### ISSUE TITLE
Difficulty returning control to JEOL when stopping Python acquisition halfway

### ISSUE THREAD

**Issue by thomasaarholt** [delmic/odemis#354]
The following is done in IPython notebook - I'm not sure if the problem is present in normal python:

If I accidentally set up an acquisition to take far longer than I anticipated, I might kill the process using CTRL + C in the terminal.

When I do that, Odemis does not return control of the microscope to the JEOL SEM we are using. We've tried things like F6 / Hitting Play/Pause and using the rectangular ROI tool without success. It's fixed by Force quitting Odemis, but that means that we have to do the full startup again.

Is there a python command I can call (after killing Python the first time) to return control to the SEM?

**Comment by pieleric** [comment]
There are mostly two aspects to your problem.

Firstly, the way the acquisition API works, indeed calling `df.get()` and stopping it half-way (with Ctrl-C) will not stop the acquisition and there is nothing but an entire full stop that will cancel the acquisition. However, if you use the `df.subscribe(callback)` + `df.unsubscribe(callback)` API, you can stop the acquisition at any time. That's what is done in the Odemis GUI. But of course that makes the code a little more complex, as you need to write a callback, something like this:
```
received_data = None
received = threading.Event()
def callback(df, da):
   df.unsubscribe(callback)
   global received_data
   received_data = da
   received.set()
```

The second aspect is the control of the JEOL SEM. It's normally taken by Odemis by using the "external" TTL signal, which is set whenever acquisition happens. However, you can override this signal from the command line:
`odemis-cli --set-attr e-beam external False`
(The acquisition will still be going on internally in Odemis, but it's the JEOL software which actually controls the SEM).

And you can put it back to "automatic" by doing:
`odemis-cli --set-attr e-beam external none`

**Comment by thomasaarholt** [comment]
Regarding the first aspect:

Currently when I'm trying, it appears that the callback will allow stopping of the acquisition *between* image frames? (assuming one is acquiring multiple frames)

That means that if a user accidentally enters an order of magnitude too high dwell time, it will only stop after the current frame is finished? 

In the case of the CL detector and doing hyperspectral imaging, will this let me stop the acquisition between individual spectra?
