### ISSUE TITLE
Hard to select a line on a sprectrum with just one line

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#36]
In the analysis tab, when the spectrum region is a thin data set, eg 200x1, it's difficult to draw a line over it.

In such a case, there is pretty much only one possibility that the user wants when selecting the line: the whole data set. So we should detect such a case (ie, on of the dimensions of the data set is 1), and then automatically create a line that goes over the whole data set.

**Comment by pieleric** [comment]
As of Odemis v2.4, data set with only one line (either horizontal or vertical) automatically cause a line to select the entire data set.
