### ISSUE TITLE
Scale of point spectrum graph always adapt to the current data

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#38]
_(requested by Toon)_
When looking at the spectrum of a point, the scale is adapted to the data. That's not always convenient when trying to compare points or to look at a specific intensity level.

So it would be nice to:
- be able to "lock/unlock" the the scale
- be able to select the min/max of the scale
  IOW, that's similar to the brightness/contrast control. The first point might be already a big improvement.

**Comment by pieleric** [comment]
Now implemented :-)
