### ISSUE TITLE
Be more careful if referencing stage fails

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#39]
If the referencing of the optical stage failed it might be a sign that the hardware is broken, or at least that it doesn't respond as we expect. Currently, if the referencing fails, a warning is displayed, and Odemis GUI continues (hoping it will work well enough to keep the user happy).

It might damage the hardware more if we keep moving it. So instead, we should warn more about this problem, and maybe even prevent using the optical stage (or eject the sample holder).

**Comment by pieleric** [comment]
Now, on any issues which happen during the stage loading, the error is displayed and the sample holder is ejected.
