### ISSUE TITLE
View in acquisition window has a very large field of view

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#45]
The SECOM/DELPHI acquisition window view shows the data of all streams. However, in some cases, this doesn't work well for the user. For instance, if the SEM stream hasn't been updated (contains data from on old location far away), and the optical stream has data from the new location, the acquisition view will be very zoomed out.

=> Center the view on the current stage location, and compute the zoom based on the theoritical FoV from each stream.

**Comment by pieleric** [comment]
Should be fixed in the next stable (2.4.5) and major (2.5) versions.
